#!/usr/local/bin/php
<?php

if ($argc < 2) {
    fwrite(STDERR, "Usage: php " . $argv[0] . " <login>\n");
    exit(1);
}

$login = $argv[1];
include('mysql.php');

$login_safe = DB_real_escape_string($login);

// Запрос индивидуальной скорости (speeddown)
$query = "SELECT `speed` FROM `userspeeds` WHERE `login` = '$login_safe'";
$result = DB_query($query);

$found_individual = false;
if ($result) {
    while ($line = DB_fetch_array($result)) {
        if (!empty($line['speed'])) {
            echo $line['speed'] . "\n";
            $found_individual = true;
            // Прерываем, так как, вероятно, ожидается одно значение
            break;
        }
    }
}

// Если индивидуальная скорость не задана — берём speedup из тарифа
if (!$found_individual) {
    $tarq = "
        SELECT `speedup`
        FROM `speeds`
        INNER JOIN (SELECT `Tariff` FROM `users` WHERE `login` = '$login_safe') AS t_u
        USING (`Tariff`)
    ";
    $tar = DB_query($tarq);
    if ($tar) {
        while ($line2 = DB_fetch_array($tar)) {
            if (!empty($line2['speedup'])) {
                echo $line2['speedup'] . "\n";
            }
        }
    }
}
?>